[build]
    command = "npm run build"
    publish = "/build"
    base = "/"



[[redirects]]
  from = "/*"
  to = "/?lang=es"
  status = 302
  conditions = {Country = ["ES"]}
  force = true

[[redirects]]
  from = "/*"
  to = "/?lang=en"
  status = 302
  force = true